version: '3.8'

services:
  backend:
    build: ./dad-jokes-app-spring
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./dad-jokes-app-angular
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - backend